name: Build LLVM
on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        bash ci.sh deps

    - name: Build LLVM
      run: |
        export USE_CCACHE=1
        bash ci.sh llvm

    - name: Upload Finished Toolchain
      uses: actions/upload-artifact@v4
      with:
        name: llvm-clang23
        path: install/
        if-no-files-found: error
